apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rsa-app-policy
spec:
  podSelector:
    matchLabels:
      app: rsa-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8000