name: 🔐 OWASP Dependency-Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y wget unzip
      - name: Clean Dependency-Check DB
        run: |
         rm -rf ~/.dependency-check
      - name: Install Dependency-Check
        run: |
         wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
          unzip dependency-check-10.0.4-release.zip -d $HOME/dependency-check
          chmod +x $HOME/dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          $HOME/dependency-check/dependency-check/bin/dependency-check.sh \
            --project "scanfield-php" \
            --scan ./ \
            --format ALL \
           
            --out ./ \
            --nvdApiKey "015e6901-821f-4276-a8f5-2f0dcba30770" \
            --disableAutoUpdate \
            --prettyPrint
          mv dependency-check-report.xml dependency-check-report-php.xml || true

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Convert report to PDF
        run: |
          if command -v wkhtmltopdf > /dev/null; then
            echo "➡ Génération du rapport PDF..."
            wkhtmltopdf dependency-check-report.html rapport-owasp-report-php.pdf
          else
            echo "⚠ wkhtmltopdf non installé, PDF non généré"
          fi

      - name: Upload Dependency-Check Reports
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-reports
          path: |
            dependency-check-report-php.xml
            dependency-check-report.html
            rapport-owasp-report-php.pdf
